---
title: "Problem Set_02"
author: "Yaqian Luo (59751503)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---
### Problem set_02 “Microbial Engines”
#### Learning objectives: 
Discuss the role of microbial diversity and formation of coupled metabolism in driving global biogeochemical cycles.

#### Specific Questions:

***What are the primary geophysical and biogeochemical processes that create and sustain conditions for life on Earth? How do abiotic versus biotic processes vary with respect to matter and energy transformation and how are they interconnected?***

*Question 1*

Tectonics and atmospheric photochemical processes are two primary geophysical processes on Earth. The biological fluxes of the six major elements-H,C,N,O,S, and P are the major biogeochemical processes.

*Question 2*

The chemical reactions abiotic and biotic processes depend on are different. Abiotic processes are based on acid-base chemistry involving formation and break of chemical bonds and transfers of protons without electrons. Biotic processes are driven by redox reactions, in which electrons and protons are both transferred. Not all of biotic processes are directly dependent on chemical bond energy. One example is photosynthesis. In terms of mass transformation, the importance of these two types of processes on biological chemical cycling is not the same. Biotic processes play significant roles in the biological fluxes of H,C,N,O, and S, while abiotic processes have contributions to the fluxes of C, S, and P.

*Question 3*

Both abiotic and biotic processes are responsible for the biogeochemical cycle of elements. Abiotic processes like erosion, geothermal activity and abiotic oxidation are able to bring the elements in sediments and atmosphere back to the biogeochemical cycle which is largely driven by biotic processes. For example, through geothermal processes, sulfate as HS^-^ and SO3^2-^ is regenerated into biochemical processes from Earth’s mantle and crust, and then contribute to the biotic processes of SO4^2-^/S respiration and anoxygenic photosynthesis.


***Why is Earth’s redox state considered an emergent property?***

Abiotic and biotic processes are formed during the evolution of biogeochemical cycle. They work together and change the redox condition of Earth's surface. As a result, the average redox state of Earth is created by feedbacks between geophysical and biological processes. 
  

***How do reversible electron transfer reactions give rise to element and nutrient cycles at different ecological scales? What strategies do microbes use to overcome thermodynamic barriers to reversible electron flow?***

*Question 1*

Element and nutrient cycles are maintained by thermodynamically favorable pathways and interactions among a variety of microbial species. 

Reversible reactions apply thermodynamically favorable pathways to sustain elements cycle under different conditions. For example, in some cases where hydrogen is sufficient, methane is generated by methanogenic Archaea through the reversible reaction using CO2 and H2 as reactants. However, at the places lack of hydrogen, methanogens consume methane because the reverse reaction is favorable in this case. 

Additionally, reversible reactions are sometimes catalyzed by the interactions between microorganisms from different species which may be temporally and spatially separated. For instance, the biogeochemical cycle of nitrogen is accomplished via cooperation of diverse microbes, including aerobic ammonium oxidizing bacteria and anaerobic denitrification bacteria. 

*Question 2*

Microorganisms use identical or near-identical pathways and cooperate with other species to overcome thermodynamic barriers. Identical or near-identical pathways, which are thermodynamically favorable in reversible reactions, may be employed. These pathways are easier for microbes to overcome thermodynamic barriers compared with their reverse processes. For instance, when hydrogen is insufficient, methane is oxidized by microbes to hydrogen, which is reverse to the formation reaction of methane performed by methanogenic Archaea. 

Besides, microbes sometimes may cooperate with multispecies for biogeochemical transformation, so that they are able to overcome thermodynamic barriers with the help from other microorganisms. Green sulfur bacteria and some Archaebacteria work with organisms able to perform citric acid cycle to get energy they need for carbon dioxide assimilation. 

***Using information provided in the text, describe how the nitrogen cycle partitions between different redox “niches” and microbial groups. Is there a relationship between the nitrogen cycle and climate change?***

*Question 1*

The biogeochemical nitrogen cycle is achieved by three sets of microbes. The first set of microbial group reduces N2 in atmosphere to NH4+ anaerobically, catalyzed by an enzyme called nitrogenase. The second set of microorganisms is responsible for the oxidization of NH4^+^ to NO3^-^ in a two-stage pathway under presence of oxygen. NH4^+^ is oxidized to NO2^-^ by ammonium oxidizing bacteria, and then NO2^-^ is subsequently oxidized to NO3^-^ by nitrate oxidizing bacteria. The third set of microbes is able to utilize NO3^-^ and NO2^-^ as electron acceptor and transform organic carbon into CO2 without oxygen. This process produces N2 to atmosphere. Therefore the nitrogen cycle is closed.  

*Question 2*

There are interactions between nitrogen cycle and climate change. Nitrogen cycle has direct and indirect impacts on global warming. N2O, a powerful greenhouse gas, is generated during the processes of nitrification as a byproduct and denitraification as an intermediate product^[1]^. The emission of N2O to atmosphere accelerates the rate of global warming. Besides, NOx, which is also emitted in nitrogen cycle, indirectly affect radiative forcing through effects on atmospheric concentrations of CH4, O3 and aerosol particulate matter^[2]^. However, the emission leads to a net cooling effect on a short time. 

Climate change is able to change nitrogen fluxes in the globally biogeochemical cycle, since it is able to alter biochemical processes involved in nitrogen cycle as well as the amount of nitrogen released to water or air. Extreme precipitation events flush more fertilizer or manure into freshwater and reduce the time for denitrification because runoff is speeded up^[2]^. Consequently, the amount of nitrogen in aquatic environments increases and the release of nitrogen gas to atmosphere declines. 

*[1] T. Usui, I. Koike, and N. Ogura, N2O Production, Nitrification and Denitrification in an Estuarine Sediment. Estuarine, Coastal and Shelf Science, 2001,52: 769-781.*

*[2] Suddick, E.C., Whitney, P., Townsend, A.R., The role of nitrogen in climate change and the impacts of nitrogen-climate interactions in the United States: foreword to thematic issue. Biogeochemistry, 2013, 114: 1-10.*

***What is the relationship between microbial diversity and metabolic diversity and how does this relate to the discovery of new protein families from microbial community genomes?***

*Question 1*

Microbial diversity may not lead to metabolic diversity. According to the modes of evolution described in the text, diverse microbial groups may perform the same metabolic pathway due to horizontal gene transfer. For example, nitrogenases genes have been widely distributed among different microbial groups on Earth, as well as methanogenesis genes. Both of them are essential to biogeochemical element cycles.    

However, by evaluating the relative depth of protein “sequence space”, the number of protein families in microbial groups is found to be linear proportional to genome size which is correlated to evolutionary rate. 

*Question 2*

Because microbial diversity is dependent on genome diversity and the number of novel protein families is linearly proportional to genome size, the number of newly discovered protein families is also linearly correlated with the size of novel genomes sequenced.  

***On what basis do the authors consider microbes the guardians of metabolism?***

Microbes are considered as the guardians of metabolism based on the fact of their ability to catalyze reactions in biogeochemical cycle and the central gene set for the ability distributed spatially and temporally. Microorganisms form Earth's environment like atmosphere through catalyzing redox reactions with enzymes translated from their genes. They using the same way control the biogeochemical cycles of nutrients and elements significant to life, such as nitrogen cycle and sulfate cycle. Although environmental selection may extinct a certain type of microbe, it is highly possible that the core gene responsible for a specific metabolic pathway in the microbial species survive in other cases. Eventually, the metabolic pathway is maintained over the long evolutionary time on Earth.   
