---
title: "Module_01_Writing_Assignment_01"
author: "Yaqian Luo (59751503)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: yes
---

###Prompt:###  
*Microbial life can easily live without us; we, however, cannot survive without the global catalysis and environmental transformations it provides.” Do you agree or disagree with this statement? Answer the question using specific reference to your reading, discussions and content from evidence worksheets and problem sets.*  

###Introduction###
Microbial engine have maintained the world for millions of years through global catalysis and environmental transformation. However things are changing in the new epoch. A new geological epoch name “Anthropocene” was proposed several years ago to describe human’s dominant impacts on Earth’s environment today [1]. Scientists have found a lot of current stratigraphic signatures caused by human disturbance distinct from that in the Holocene. Besides, technology and its exponential growth rate allow humans obtain the ability to alter the world at present or in the near future. There is even a saying that humans are able to survive without microbial support, because we can transform environments faster than microbes and control the direction of transformation to make environment more favorable to our life and activities. However, I still believe that humans can only survive in a world with microbes. One of the major reasons is that microbes are the engine of elements cycles and creates the environment sustaining our life. Secondly, there are still a plenty of biochemical pathways that we do not fully understand, making it difficult to replace microbes. And also, microbes can help us solve global issues we are encountering today like food scarcity and environmental pollution. I think they are our most reliable friends. 

###Microbes can easily live without us###	

There is no doubt that microbes can live on Earth easily without human beings, since they have been present on Earth for a longer time than humans and have huge abundance. Their ability to transfer genes horizontally and form protective cellular structure allow them survive unfavorable situations. 

Microbial history on Earth is an extraordinarily long story. At least 3.5 billion years ago, microbes appeared on Earth, and form Earth to what it looks like today [2]. However, as a mammal species, humans just started to stand on the stage of Earth around 200,000 years ago [3]. In addition, microbes are distributed almost everywhere on the planet, may be from marine subsurface about 15 km below the sea level to the atmosphere at an altitude of 57-77 km [4]. In contrast, the terrestrial surface of Earth is the major habitat for humans. Several factors help microbes exist on Earth over a vast span of evolutionary time. They are large species abundance, horizontal gene transformation and the specific cellular structure.   

Due to the large abundance and wide distribution of microbial species and genes, it is impossible to wipe out all of microbial species from our planet, as long as life continues to exist on earth. Microbial abundance is difficult to count. The number of prokaryotes on earth is roughly estimated to be 4-6×10^30^ cells[4], and microbial abundance in subseafloor sedimentary is reported to be 2.9×10^29^ cells [5]. Based on these figures with high magnitude, it is easily concluded that the number of microbes on the globe is extraordinarily huge. The large abundance enables microbes to mutate, acquire genetic diversity and form novel species at a high speed, and then easily adapt to new living conditions under environmental pressures [4][6]. One example is nitrogenase, an enzyme significant to nitrogen fixation and is irreversibly inhibited by oxygen. Nitrogen-fixing organisms have evolved mechanisms to protect nitrogenase from oxygen in order to survive in aerobic environment [6].  

What’s more, some central genes for biogeochemical cycles are horizontally transferred among microbial species, such as dissimilatory sulfite reductases and ammonia monooxygenases genes [6] for sulfate and nitrogen cycle respectively. As a result, even though a specific microbial species become extinct by negative natural selection, other alternative microbial species can take its place and occupy the ecological niche to keep elements cycles continuing. 

Besides, some microbial species are able to protect themselves from disadvantageous environments by forming a dormant cellular structure called endospore. This structure has high resistantance to detrimental living conditions like ultraviolet radiation, desiccation, high temperature and freezing, and can survive for a long period of time [7]. It is reported that endospores of Antarctic bacteria are capable of keeping dormant at a temperature of -14℃ for more than 10,000 years[8]. endospores also contain microbial genetic information. Thus it can revive itself to vegetative cells when environment becomes favorable. Bacillus and Clostridium are two examples of bacteria able to form endospore. This self-protective cellular structure may be helpful for microbes to endure several global mass-extinction episodes and keep alive over the millions of years. 

###Human needs microbes###

Human, however, is not able to live in a world without microbes. Microbes create a habitable living condition we are dependent on by catalyzing biogeochemical cycles and transforming Earth’s environment, while we are unable to mimic these biochemical processes on our own. Another reason is that microbes can help us to resolve some global issues we are facing today. 
  
####Microbes form our living environment####

Microbes form our living environment by making contributions in biogeochemical cycles and the evolution of Earth’s environment as well as constructing the inner environment for our bodies. 

Earth’s environment is affected by microbes through biogeochemical cycles. Six essential elements-H, C, N, O, S, and P- are the building blocks for all of living organisms on Earth, including human, to form their genetic information and cellular structures. The global element cycles largely driven by microbially catalyzed redox reactions, introduce these elements into biosphere from abiotic environment [6]. For example, nitrogenase, an enzyme produced by microbes, catalyzes the redox reaction converting nitrogen gas in atmosphere into ammonium which is then oxidized to nitrate and absorbed by plants and animals through food chains. Although there are non-biological processes like lightning able to fix nitrogen, the biological process described above is the predominant pathway. Therefore, these six essential elements might not be available for humans, if the microbial links between abiotic environment and biosphere in the global cycles were broken. 

Microbes also play significant roles in the evolution of Earth’s environment. The evolution of the structure of microbial mats might result in the emergence of photosynthesis around 3.5 billion years ago, which equipped atmosphere with oxidation power, increased microbial productivity, and allowed organisms to live freely on the planet [3]. After 1.3 billion years, green bacteria with chloroplasts working with other microbial species increased atmospheric oxygen level drastically [3]. Besides, microbes make substantial contributions to the formation of modern atmosphere. Most of oxygen we breathe today is not from terrestrial photosynthesis, but from marine photosynthesis performed mostly by microorganisms like eukaryotic algae and cyanobacteria [9]. Thus, it can be imagined that humans might die due to shortage of atmospheric oxygen if microbes stopped producing oxygen.  

In addition to impacting the external environment, microbes also have effects on our health. The relationship between some microbial species and humans is mutualism, which means we cannot life healthily without these microorganisms. For instance, we get benefits from gastrointestinal microbiota fermenting dietary fiber into short-chain fatty acids, which are then utilized as energy and nutrients and oxidized to carbon dioxide through respiration process in our bodies [10]. This microbial community also helps us to adsorb essential minerals like calcium and iron and synthesize some important compounds, such as vitamin B and xenobiotics. Therefore we might not be able to gain sufficient energy and nutrients to sustain our life without gastrointestinal microbiota.    

####Human technology cannot replace microbes####

Although scientific technology has developed rapidly over the past few decades and will continue to grow at an unprecedented rate, we will still rely on the environmental conditions provided by microbes in the foreseeable future. The main reason is the hardness to comprehend all microbial metabolisms and replace microbial functions in biogeochemical cycles due to microbes’ high mutation rate and lack of sufficient information. 

It is extremely difficult for humans to fully understand, manipulate or even mimic all microbial metabolisms because of their complexity and diversity. Until now, the biological processes for nitrogen cycle are still being investigated. New microbial species, such as ammonia-oxidizing archaea [11] and comammox [12], are discovered recently and revise our understanding on nitrogen cycle. But their relationships with ammonia-oxidizing bacteria and nitrite-oxidizing bacteria are still a mystery. Additionally, it is estimated that there about one trillion species of microbes on Earth, while 99.999 percent of them have not been discovered [13]. As a result, it is highly possible that there are some species that are of importance in biogeochemical cycles but have not been discovered by humans.

The high mutation rate of microbial genes is another factor that obstructs our comprehension on microbial mechanisms. With the assumption of a prokaryotic mutation rate of 4×10^-7^ mutations per gene per DNA replication, Whitman et al. calculated four simultaneous mutation in every gene shared by the population of marine heterotrophs and soil prokaryotes at high rate of once every 0.4 and 3.4 hours [4]. The high mutation rate leads to the high-speed changes of genetic diversity, and consequently novel mechanisms are created that are difficult to detect at the first time and first place.

Lack of comprehensive information on microbes, it is really hard for us to perform biochemical mechanisms artificially and replace microbes in the global biogeochemical cycles. And also we do not have sufficient knowledge on the intricate relationships among microbial species and between microbes and abiotic environment. We might underestimate the significance of some mechanisms to the global environment. As a result, the likelihood to generate a favorable condition for human life by ourselves is very small, even if technology is advanced enough to allow humans to mimic microbial mechanisms.

####We still need microbes to solve global issues####

Microbes not only form a habitable environment for humans, but also play critical roles in human activities and help us address global issues like famine and environmental pollution. For instance, we develop genetic engineering technology to form new cells with targeting genes which are able to generate certain proteins and applied in a variety of industries like food production and diseases treatment. This technology need to use microbial cells to achieve gene-engineered bacteria. Another example is wastewater treatment. In order to prevent eutrophication in aquatic environment, bacteria involved in nitrogen and phosphorus cycles, such as ammonium oxidizing bacteria and polyphosphate-accumulating organisms, are employed in wastewater treatment processes to remove nitrogen and phosphate from the effluent [14].  

###Conclusion###

Thanks to microbes for providing such a wonderful place with abundant nutrients and perfect atmosphere for us, and helping us resolve our social, economic and environmental issues. They are amazing organisms with simple cellular structures compared with human, but too complex to been completely understood. It is hard to imagine a world without microbes. But one thing is definite that human cannot survive in such a world. Since we are so relied on these powerful organisms, we should cooperate with them to mitigate our negative impacts on Earth which is the home not just for us but also for every living species.     

###References###

[1] C. N. Waters, J.Zalasiewicz, C. Summerhayes, “The Anthropocene is functionally and stratigraphically distinct from the Holocene,” *Science*, vol.351, issue 6269, pp. 2622/1-2622/10, Jan. 2016.

[2] E.G. Nisbet and N.H. Sleep, “The habitat and nature of early life,” *Nature*, vol.409, pp. 1083-1091, Feb. 2001. 

[3] D. P. Schrag, “Geobiology of the anthropocene,” in *Fundamentals of Geobiology*, 1st edition, Blackwell Publishing Ltd., 2012, pp. 425-436.

[4] W. B. Whitman, D. C. Coleman, and W. J. Wiebe, “Prokaryotes: The unseen majority,” *Pro. Natl. Acad. Sci.*, vol. 95, pp. 6578-6583, June 1998. 

[5] J. Kallmeyer, R. Pockalny, and R. R. Adhikari, “Global distribution of microbial abundance and biomass in subseafloor sediment,” *PNAS*, pp. 1-4.   

[6] P. G. Falkowski, T. Fenchel, and E. F. Delong, “The microbial engines that drive earth’s biogeochemical cycles,” *Science*, vol.320, pp. 1034-1039, May 2008.  

[7] *Endospore* (n.d.) [Online]. Available: https://en.wikipedia.org/wiki/Endospore 

[8] J. G. Black, “Characteristics of Prokaryotic and Eukaryotic Cells,” in *Microbiology: principles and explorations*, 7th edition, Wiley, 2011, pp. 90-93.  

[9] J. F. Kasting and J. L. Siefert, “Life and the evolution of earth’s atmosphere,” *Science*, vol.296, pp. 1066-1068, May 2002. 

[10] *Gut flora* (n.d.) [Online]. Available: https://en.wikipedia.org/wiki/Gut_flora#Functions 

[11] R. Hatzenpichler, “Diversity, physiology, and niche differentiation of ammonia-oxidizing archaea,” *Applied Environmental Microbiology*, vol.78, pp. 7501-7510, Nov.2012. 

[12] D. Holger, E.V. Lebedeva, P. Pjevac, P. Han, C. Herbold, M. Albertsen, N. Jehmlich, M. Palatinszky, J. Vierheilig, A. Bulaev, R. H. Kirkegaard, M. von Bergen, T. Rattei, B. Bendinger, P.H. Nielsen, M. Wanger “Complete nitrification by Nitrospira bacteria,” *Nature*, doi:10.1038/nature16461.

[13] N. Bakalar. (2016, May 23). *Earth May Be Home to a Trillion Species of Microbes* [Online]. Available:  https://www.nytimes.com/2016/05/24/science/one-trillion-microbes-on-earth.html 

[14] Metcalf and Eddy, *Wastewater engineering treatment and reuse*, 4th Edition, McGraw Hill, 2003.

