---
title: "Module_01_Problem Set_01"
author: "Yaqian Luo (59751503)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---
### Problem set_01 ““Prokaryotes: The unseen majority”  

#### Reading:  
W. B. Whitman, D. C. Coleman, and W. J. Wiebe, "Prokaryotes: The unseen majority," *PNAS*, vol. 95, pp. 6578-6583, June 1998. (http://www.pnas.org/content/95/12/6578)

#### Learning objectives: 
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.

#### Specific Questions:

***What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.*** 

*Qrestion 1*   
The primary prokaryotic habitats are aquatic environments, soil, and subsurface.

*Question 2*  
Aquatic environments: Prokaryotic cell abundance is in huge variance under different aquatic conditions. The average of cellular density for prokaryotes decreases from 5 ×10^5^ cells/ml in upper 200m of the open ocean to 5 ×10^4^ cells/ml where the depth is over 200m. Although cellular density in freshwaters and saline lakes is about 106 cells/ml and higher than that in seawater, the total cell number of prokaryotes in these two kinds of aquatic ecosystems is three orders of magnitude below the number in seawaters, due to small volume compared to seawater. Cell abundance in polar region contributes to a small portion of the total cellular number in aquatic environments.

Soil: Huge difference in prokaryotic cell abundance also exists among different types of soils. The number of prokaryotes in forest soils is much less than that in others among which there is little variance.

Subsurface: cell density declines with depth in unconsolidated subsurface sediments. It is estimated in the paper that 97% of prokaryotic cells in unconsolidated sediment occur at depth no more than 600m.  

*Question 3*  
The total number of prokaryotic cells on Earth is 415-640×10^28^. The number in aquatic habitats, soil and subsurface are 11.8×10^28^, 25.6×10^28^, and 380-605×10^28^, respectively.

***What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?***

The estimated prokaryotic cell abundance in the upper 200m of the ocean is 3.6×10^28^ cells.

The portion of marine cyanobacterium is 8% calculated as below:
4×10^4^ cells/ml÷5×10^5^ cells/ml×100% = 8%

This ratio affects the capability of ocean to capture carbon dioxide from atmosphere, since cyanobaterium obtains energy by photosynthesis which is a process involving carbon dioxide as a reactant. Cyanobacterium also has huge contributions to the formation of modern atmosphere. They are a net source of oxygen, and even in some cases they are the only source of oxygen. This kind of prokaryotes is also responsible for nitrogen fixation^[1]^. Therefore, cyanobacterium plays a significant role in the atmospheric composition. 

*[1] James F. Kasting and Janet L. Siefert, Life and the Evolution of Earth’s Atmosphere. Environmental Microbiology, 2002, 296, 1066-1068.* 


***What is the difference between an autotroph, heterotroph, and a lithotroph based on information provided in the text?***

The way to obtain materials to support its own life is different between autotroph, heterotroph, and lithotroph. Autotroph is able to produce complex organic compounds using inorganic carbon (like carbonate) and energy from light or chemical reactions. For heterotroph, organic carbon is their carbon as well as energy source. Lithotroph obtains energy from inorganic substrate (such as ammonium).


***Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?***

The deepest habitat may be the subsurface with a depth of 15 km below sea level and 4 km below the Mariana Trench (about 11 km below sea level^[2]^). 

Temperature is the primary limiting factor under this circumstance, because temperature at this depth is about 125℃, which is close to maximal temperature for prokaryotic life.

*[2] Deepest Part of the OceanI (n.d.)[Online]. Available: https://geology.com/records/deepest-part-of-the-ocean.shtml *

***Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?***

The highest habitat for prokaryotes may be in the atmosphere at an altitude of 57-77 km. 

The primary limiting factor in this case may be nutrient and UV. There are several essential materials for prokaryotic life, such as phosphate, which are scarce at this altitude. UV is another inhibitive factor to prokaryotic life because it can destroy DNX or RNA chain and it is not absorbed at this altitude due to lack of ozone in atmosphere^[3]^. Therefore, nutrient and UV may be the dominant factors for prokaryotic life at the highest habitat.

*[3]Ozone layer (n.d.) [Online]. Available: https://en.wikipedia.org/wiki/Ozone_layer *


***Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth’s biosphere measured in km?***

The deepest habitat for prokaryotic life may be around 15 km below the sea level and the highest habitat may be 57-77 km above the ground. So the vertical distance of biosphere on Earth is about 72-92 km.


***How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)***

The cellular production rate is calculated using the formula below:  
cellular production rate = Population size × 365 days/yr ÷ turnover time

e.g.  For Marine heterotrophs in the upper 200 m of the open sea, there is:  
cellular production rate = 3.6×10^28^ cells×365 days/yr÷16 days = 8.2×10^29^ cells/yr


***What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?***

*Question 1*  
Large amount of carbon available for prokaryotes and high carbon assimilation efficiency accelerate prokaryotes’ turnover rates. However, prokaryotes in the ocean need more carbon and their turnover rates decrease when carbon assimilation efficiency is low. 

The turnover rate of prokaryotes living in the upper 200m of the ocean is calculated as follows:  
Total amount of cellular carbon for prokaryotes in the upper 200m of the ocean is :  
3.6×10^28^ cells × 20 fg C/cell = 0.72 Pg C  
The amount of net productivity to support prokaryotes is:  
0.72 Pg C×4 = 2.88 Pg C  
Net primary carbon productivity in marine consumed by prokaryotes in the upper 200m is:  
51 Pg C/yr×85% = 43 Pg C/yr  
Turnover rate for heterotrophs in upper 200m ocean is:  
43 Pg C/yr ÷2.88 Pg C=14.9/yr  

*Question 2*  
The average turnover time rises with depth in the ocean. One reason may be that temperature in the deep ocean is lower than that in the upper ocean, which declines the efficiency of carbon assimilation. Another possible cause is the amount of carbon content needed to support prokaryotes’ life increases with depth in the ocean, since cell abundance in deep oceanic water is larger than that in the upper ocean. As a result, the average turnover time for prokaryotes rises in deeper ocean. 

The calculated average turnover time for prokaryotes living in terrestrial habitats is far larger than that in marine environment. There are several possible explanations for the difference. Firstly, the required amount of carbon content for prokaryotes in terrestrial habitats may be overestimated, because there are other metabolic activities detected like sulfate reduction and lithoautotrophic processes for the growth of prokaryotes in terrestrial habitat. Secondly, subsurface biomass may be overestimated and carbon assimilation efficiency may be underestimated when turnover rates of prokaryotes in subsurface is calculated. Therefore, the calculated result for terrestrial habitats may be larger than the real value.   


***How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10^-7^ per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)***

The calculation for average mutation rate is presented below.  
Mutation frequency (/yr) = mutation rate × cell abundance× turnover rate (/yr)  
Mutation time (hr) = 365 day/yr×24 hr/day÷mutation frequency (/yr)  

Take marine heterotrophs in the upper 200 m as an example:   
Mutation rate for four simultaneous mutation is:  
(4×10^-7^)^4^ = 256×10^-28^ per generation  
Mutation frequency is:  
256×10^-28^per generation × 3.6 ×10^28^ cells × 365 day/yr ÷ 16 day = 21024/yr  
Mutation time is:  
365 day/yr×24 hr/day÷21024/yr = 0.4 hr


***Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt?***

High mutation rate leads to large genetic diversity and high potential to form new species. Large population size and high mutation rate increase prokaryotes’ ability to survive in extreme environments.

Point mutations are not the only way for microorganisms to obtain genomic diversity and new phenotypes. For eukaryotic microorganisms like fungi and green algae, DNA in their cells is arranged in complex chromosomes. Hence large-scale mutations like amplifications and inversions are another approach for eukaryotic microorganisms to increase their genomic diversity. However, point mutations are the only way for prokaryotes to diversify their genomes and gain new adaptation, because they do not have chromosomal structure.


***What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text?***

There is a large diversity of prokaryotes on Earth due to their large abundance and high mutation rate. Large abundance and high mutation rate increase the probability for prokaryotes to form new genetic sequence, as a result, may obtain new phenotypes.   After several genetic mutations, a new species is generated, which can be completed within a short period of time like days or months. Prokaryotes present on Earth for millions of years. Thus, they have evolved into millions of species, some of which have not been discovered yet.  

Due to the high prokaryotic diversity, their metabolic activities are different from each species. Autotrophs, heterotrophs, and lithoautotrophs are three major metabolisms for prokaryotes, which enable them to use a wide range of materials to support their life, such as methanol, iron and ammonium, and survive in anaerobic and aerobic environments and a variety of ecosystems including marine, soil and subsurface.   

Although single cell is very small and its metabolic potential is negligible, the metabolic potential of all kinds of prokaryotic cells cannot be ignored due to the huge number of prokaryotic cells. They have huge impacts on Earth’s biogeochemical transformation. For example, prokaryote in the ocean is one of the major atmospheric oxygen sources and has huge effects on the nitrogen cycle. 

