---
title: "Evidence_worksheet_01"
author: "Yaqian Luo (59751503)"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Evidence Worksheet for "Prokaryotes: The Unseen Majority"


### Learning Objectives
Describe the numerical abundance of microbial life in relation to ecology and biogeochemistry of Earth systems.


### General Questions
#### What were the main questions being asked?

The questions are: What are the actual number of prokaryotes? and what total amount of their carbon content on earth?


#### What were the primary methodological approaches used?

The primary methodological approaches used in the paper are classification, literature survey, and comparison. Classification is for the estimation of prokaryotic abundance, literature survey is for data collection, and comparison method is for comprehension of the estimated results. 

Since prokaryote is ubiquitous on Earth, classification of its habitats is helpful to estimate the number of prokaryotes and the amount of carbon content in microbes. Prokaryotes’ habitats generally include aquatic environments, soil, subsurface, and others like animals, leaves, and air. The first three habitats are concerned, because they have been proved in the paper to be the major place for prokaryotes. For each of them, they are divided into several groups for estimation. For example, subsurface consists of marine subsurface and terrestrial subsurface, and different methods and values are applied to determine the number of prokaryotes and carbon content in different kind of subsurface. 

Literature survey is the major approach for data collection, because it is the simplest and quickest method to obtain data needed. For the calculations of number of prokaryotes, values of cellular density, habitat volume or area, and relative parameters are collected from abundant literatures. 

Comparison is another major approach used in the paper. The estimated results are huge and kind of beyond our imagination. Comparison is an effective way to help readers comprehend these enormous numbers by associating them with those numbers easy to understand. In the paper, prokaryote is contrasted with plant, in order to justify the abundance of prokaryotic carbon and nutrients.    


#### Summarize the main results or findings. 

The number of prokaryotes and total amount of their cellular carbon on earth are 4-6×10^30^ cells and 350-550 Pg of C, respectively. Prokaryotic carbon is substantial, about 60-100% of total carbon in plants. Aquatic environments, soil, and subsurface are three dominant habitats for earth’s prokaryotes, in which the number of prokaryotic cells are calculated to be 1.2×10^29^, 2.6×10^29^, 3.75-6.0×10^30^, respectively, the amount of carbon content in prokaryotes are 2.2 Pg of C, 26 Pg of C, and 325-519 Pg of C, respectively, and turnover time for heterotrophic prokaryotes is 6-25 days, 0.8 yr, and 2.5 yr, respectively. The annual cell production for prokaryotes is highest in the open ocean.


#### Do new questions arise from the results?

Some new questions are raised based on the results of the study. They are:

1.It has already been proved in the paper that prokaryotes are abundant and have huge carbon and nutrient contents. However, it is still not clear that whether prokaryote is the largest living reservoir for carbon and essential elements on earth.

2.Based on the results of turnover time for prokaryotes in different habitats, a question needs to be answered that why the turnover time for prokaryote in subsurface is far longer than that in other ecosystem.

3.Prokaryotes have huge potential to obtain genetic diversity and a large number of species, due to their large population size and quick turnover time. Nevertheless, we are not sure that whether the current definition of a prokaryotic species is consistent with the real definition, and there may be some taxonomic tribes being grouped into the same species. 


#### Were there any specific challenges or advantages in understanding the paper (e.g. did the authors provide sufficient background information to understand experimental logic, were methods explained adequately, were any specific assumptions made, were conclusions justified based on the evidence, were the figures or tables useful and easy to understand)? 

There are several advantages and challenges in comprehending the paper:

1.Habitats are redefined in the paper, which is helpful for understanding methods used in the estimation and making more accurate calculations. For example, subsurface in the paper refers to terrestrial habitats below 8 m and marine sediments below 10 cm, not including upper 10 cm of marine sediments that is a part of aquatic environments according to the paper.

2.The estimation of prokaryotic abundance and turnover time involves a lot of calculation. However, formulas for calculations are not presented in the paper, making it difficult for readers to understand the results and researchers to replicate the study. For example, it is hard to figure out how to calculate the generation time for prokaryotes in upper 200m of the ocean based on the efficiency of carbon assimilation and the amount of net productivity without any relevant formulas in the paper.

3.Assumptions are often made during the estimation of prokaryotic abundance and carbon contents. They are useful to obtain final results, but also show deficiencies of calculation approaches need to be solved in the future studies. For instance, there are two methods introduced for the estimation of terrestrial subsurface prokaryotes’ abundance. Both of them make some assumptions. The average porosity of terrestrial subsurface is assumed to be 3% in the first approach, while the ratio of unattached prokaryotes in aquifer is considered to be consistent for the second approach. As a result, it is reported that the number of prokaryotes in terrestrial subsurface falls into a range of 2.5-25×10^29^ cells, which needs more accuracy in the further research.  


