---
title: "Evolutionary Development of Earth"
author: "Julia Beni"
date: "version `r format(Sys.time(), '%B %d, %Y')`"
runtime: shiny
output:
  html_document: 
    toc: yes
    toc_float: 
      collapsed: false
editor_options: 
  chunk_output_type: console
---

```{r, eval=FALSE}
install.packages("plotly")
install.packages("shiny")
```
  
  
### Interactive timeline for the development of the Earth  


```{r echo=FALSE, warning=FALSE, message=FALSE}
tics <-rep(0,14)

Million.years.ago<-c(4600,4500,4400,4200,3800,3750,3500,3000,2700,2200,2100,1300,0.550,0)

events<-c("Solar system formed","formation of moon giving Earth spin and tilt, day/night cycles & seasons","formation of oceans and early atmosphere","Darwinian threshold",
          "prokaryotic cells, Rubisco, stable sea chemistry, halted meteorite bombardment","photosynthesis","cyanobacteria","eukaryotic cells",
          "great oxidation event, Red Beds","first snowball Earth","appearance of multicellular life", "animals","humans","today")

epoch<-c(rep("Hadean",4),rep("Archaen",5),rep("Proterozoic",3),rep("Phanerozoic",2))

ddd<-data.frame(tics,Million.years.ago,events,epoch)

library(plotly)
library(shiny)

ay <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)

ax <- list(
  title = "Million years ago"
)

plot_ly(ddd, x = ~Million.years.ago, y = ddd$tics, type = "scatter",

  text = ~paste(events),
  color = ~epoch
) %>%
  layout(title="Evolutionary Development of Earth", xaxis = ax, yaxis = ay)
```
  
#### Physical and chemical characterization of Earth epochs  


```{r echo=FALSE, warning=FALSE, message=FALSE}

e2<-c("Hadean","Archaen","Proterozoic","Phanerozoic")

chr<-c("dry surface at 500 degrees C, 90 bar pressure on Earth's surface; carbon dioxide tied up in carbonate materials such as limestone", "strong greenhouse gases predominate (methane and carbon dioxide)", "oxidation of the early atmosphere - microaerobic", "increased oxygenation of the atmosphere, mass extinction events from meteorite impacts")

ab<-as.data.frame(cbind(e2,chr),stringsAsFactors = FALSE)

selectInput("Epoch","Epoch:",choices=e2)

renderPrint({
  ab$chr[ab$e2==input$Epoch]
})

```
  
 